### ISSUE TITLE
API examples inconsistent with definitions

### ISSUE THREAD

**Issue by avenjamin** [cobinhood/cobinhood-api-public#1]
Hi

In many of the examples on the README it shows:

side: “buy”

However the definition shows that side is an enum(“bid”, “ask”). 

I understand the API is still being heavily developed but just thought I’d flag anyway in case you keep those examples  :)

**Comment by aitjcize** [comment]
Hey @avenjamin 

Sorry for the inconsistency in the docs. `bid` and `ask` is the right enum to use. I'll update the document shortly. Thanks.

**Comment by aitjcize** [comment]
Fixed in https://github.com/cobinhood/cobinhood-api-public/commit/22d19e6aaa82b9ec6e02991edd26a679350fac80
